### ISSUE TITLE
Unable to create custom lobby with schematic.

### ISSUE THREAD

**Issue by Shipi1** [Mezy/PlayUHC-Community#6]
I put my "lobby.schematic" on 'plugins/PlayUHC', first tried with the schem copied from MC Edit, and didnt work, and i though, "maybe its because i didnt do it with worldedit", so i copied it from WorldEdit and didnt work either.

Plugins installed are WorldEdit 7.0.0 beta 04, PlayUHC and WorldBorder.

Here is my console log.

[Server thread/WARN]: [PlayUHC] Task #2 for PlayUHC v1.9.3 generated an exception
java.lang.NoClassDefFoundError: com/sk89q/worldedit/LocalWorld
	at com.gmail.val59000mc.playuhc.mc1_13.schematics.Lobby.build(Lobby.java:50) ~[?:?]
	at com.gmail.val59000mc.playuhc.mc1_13.game.GameManager.loadWorlds(GameManager.java:279) ~[?:?]
	at com.gmail.val59000mc.playuhc.mc1_13.game.GameManager.startWaitingPlayers(GameManager.java:183) ~[?:?]
	at com.gmail.val59000mc.playuhc.mc1_13.game.GameManager.loadNewGame(GameManager.java:157) ~[?:?]
	at com.gmail.val59000mc.playuhc.PlayUhc$1.run(PlayUhc.java:30) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:888) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.LocalWorld
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	... 12 more

**Comment by Mezy** [comment]
Please use the latest stable version of worldedit from this page (Don't use beta versions): https://dev.bukkit.org/projects/worldedit

**Comment by Mezy** [comment]
Sorry didn't know this was the only working version for 1.13. I added support now.
